name: Publish Master

on:
  push:
    branches: 
      - master

jobs:
  publish_to_workshop:
    name: Publish to Steam Workshop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout repository      
        run: echo VERSION=$(echo ${GITHUB_REF:11}) >> $GITHUB_ENV
      
      - name: workshop-upload
        uses: arma-actions/workshop-upload@v1
        with:
          appId: '394360'    # default
          itemId: '2263932526' # Id of item to update
          changelog: 'https://github.com/akushnikov/nma/releases/tag/v${{ env.VERSION }}'
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
  
