name: Publish Master

on:
  push:
    branches: 
      - master

jobs:
  publish_to_workshop:
    name: Publish to Steam Workshop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v2
        run: echo ::set-env name=VERSION::$(echo ${GITHUB_REF:11})
  
